# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# Using CodeCov: https://github.com/codecov/example-r

language: R
r: bioc-devel
warnings_are_errors: true
sudo: required
cache: packages

before_install:
  - sudo apt-get update
  - sudo apt-get install libnetcdf-dev

#r_build_args: "--no-build-vignettes"
#r_check_args: "--no-build-vignettes"

r_packages:
  - covr

script: 
  - |
    travis_wait 40 R CMD build .
    travis_wait 40 R CMD check --no-vignettes IPO*tar.gz

#after_success:
#  - travis_wait 40 Rscript -e 'library(covr); codecov()'
